# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 0, size: 0.065, name: Tag0},
    {id: 1, size: 0.065, name: Tag1},
    {id: 2, size: 0.065, name: Tag2},
    {id: 3, size: 0.065, name: Tag3},
    {id: 4, size: 0.065, name: Tag4},
    {id: 5, size: 0.065, name: Tag5},
    {id: 6, size: 0.065, name: Tag6},
    {id: 7, size: 0.065, name: Tag7},
    {id: 8, size: 0.065, name: Tag8},
    {id: 9, size: 0.065, name: Tag9},
    {id: 10, size: 0.065, name: Tag10},
    {id: 11, size: 0.065, name: Tag11},
    {id: 12, size: 0.065, name: Tag12},
    {id: 13, size: 0.065, name: Tag13},
    {id: 14, size: 0.065, name: Tag14},
    {id: 15, size: 0.065, name: Tag15},
    {id: 16, size: 0.065, name: Tag16},
    {id: 17, size: 0.065, name: Tag17},
    {id: 18, size: 0.065, name: Tag18},
    {id: 19, size: 0.065, name: Tag19},
    {id: 20, size: 0.065, name: Tag20},
    {id: 21, size: 0.065, name: Tag21},
    {id: 22, size: 0.065, name: Tag22},
    {id: 23, size: 0.065, name: Tag23},
    {id: 24, size: 0.065, name: Tag24},
    {id: 25, size: 0.065, name: Tag25},
    {id: 26, size: 0.065, name: Tag26},
    {id: 27, size: 0.065, name: Tag27},
    {id: 28, size: 0.065, name: Tag28},
    {id: 29, size: 0.065, name: Tag29},
    {id: 30, size: 0.065, name: Tag30},
    {id: 31, size: 0.065, name: Tag31},
    {id: 32, size: 0.065, name: Tag32},
    {id: 33, size: 0.065, name: Tag33},
    {id: 34, size: 0.065, name: Tag34},
    {id: 35, size: 0.065, name: Tag35},
    {id: 36, size: 0.065, name: Tag36},
    {id: 37, size: 0.065, name: Tag37},
    {id: 38, size: 0.065, name: Tag38},
    {id: 39, size: 0.065, name: Tag39},
    {id: 40, size: 0.065, name: Tag40},
    {id: 41, size: 0.065, name: Tag41},
    {id: 42, size: 0.065, name: Tag42},
    {id: 43, size: 0.065, name: Tag43},
    {id: 44, size: 0.065, name: Tag44},
    {id: 45, size: 0.065, name: Tag45},
    {id: 46, size: 0.065, name: Tag46},
    {id: 47, size: 0.065, name: Tag47},
    {id: 48, size: 0.065, name: Tag48},
    {id: 49, size: 0.065, name: Tag49},
    {id: 50, size: 0.065, name: Tag50},
    {id: 51, size: 0.065, name: Tag51},
    {id: 52, size: 0.065, name: Tag52},
    {id: 53, size: 0.065, name: Tag53},
    {id: 54, size: 0.065, name: Tag54},
    {id: 55, size: 0.065, name: Tag55},
    {id: 56, size: 0.065, name: Tag56},
    {id: 57, size: 0.065, name: Tag57},
    {id: 58, size: 0.065, name: Tag58},
    {id: 59, size: 0.065, name: Tag59},
    {id: 60, size: 0.065, name: Tag60},
    {id: 61, size: 0.065, name: Tag61},
    {id: 62, size: 0.065, name: Tag62},
    {id: 63, size: 0.065, name: Tag63},
    {id: 64, size: 0.065, name: Tag64},
    {id: 65, size: 0.065, name: Tag65},
    {id: 66, size: 0.065, name: Tag66},
    {id: 67, size: 0.065, name: Tag67},
    {id: 68, size: 0.065, name: Tag68},
    {id: 69, size: 0.065, name: Tag69},
    {id: 70, size: 0.065, name: Tag70},
    {id: 71, size: 0.065, name: Tag71},
    {id: 72, size: 0.065, name: Tag72},
    {id: 73, size: 0.065, name: Tag73},
    {id: 74, size: 0.065, name: Tag74},
    {id: 75, size: 0.065, name: Tag75},
    {id: 76, size: 0.065, name: Tag76},
    {id: 77, size: 0.065, name: Tag77},
    {id: 78, size: 0.065, name: Tag78},
    {id: 79, size: 0.065, name: Tag79},
    {id: 80, size: 0.065, name: Tag80},
    {id: 81, size: 0.065, name: Tag81},
    {id: 82, size: 0.065, name: Tag82},
    {id: 83, size: 0.065, name: Tag83},
    {id: 84, size: 0.065, name: Tag84},
    {id: 85, size: 0.065, name: Tag85},
    {id: 86, size: 0.065, name: Tag86},
    {id: 87, size: 0.065, name: Tag87},
    {id: 88, size: 0.065, name: Tag88},
    {id: 89, size: 0.065, name: Tag89},
    {id: 90, size: 0.065, name: Tag90},
    {id: 91, size: 0.065, name: Tag91},
    {id: 92, size: 0.065, name: Tag92},
    {id: 93, size: 0.065, name: Tag93},
    {id: 94, size: 0.065, name: Tag94},
    {id: 95, size: 0.065, name: Tag95},
    {id: 96, size: 0.065, name: Tag96},
    {id: 97, size: 0.065, name: Tag97},
    {id: 98, size: 0.065, name: Tag98},
    {id: 99, size: 0.065, name: Tag99},
    {id: 100, size: 0.065, name: Tag100},
    {id: 101, size: 0.065, name: Tag101},
    {id: 102, size: 0.065, name: Tag102},
    {id: 103, size: 0.065, name: Tag103},
    {id: 104, size: 0.065, name: Tag104},
    {id: 105, size: 0.065, name: Tag105},
    {id: 106, size: 0.065, name: Tag106},
    {id: 107, size: 0.065, name: Tag107},
    {id: 108, size: 0.065, name: Tag108},
    {id: 109, size: 0.065, name: Tag109},
    {id: 110, size: 0.065, name: Tag110},
    {id: 111, size: 0.065, name: Tag111},
    {id: 112, size: 0.065, name: Tag112},
    {id: 113, size: 0.065, name: Tag113},
    {id: 114, size: 0.065, name: Tag114},
    {id: 115, size: 0.065, name: Tag115},
    {id: 116, size: 0.065, name: Tag116},
    {id: 117, size: 0.065, name: Tag117},
    {id: 118, size: 0.065, name: Tag118},
    {id: 119, size: 0.065, name: Tag119},
    {id: 120, size: 0.065, name: Tag120},
    {id: 121, size: 0.065, name: Tag121},
    {id: 122, size: 0.065, name: Tag122},
    {id: 123, size: 0.065, name: Tag123},
    {id: 124, size: 0.065, name: Tag124},
    {id: 125, size: 0.065, name: Tag125},
    {id: 126, size: 0.065, name: Tag126},
    {id: 127, size: 0.065, name: Tag127},
    {id: 128, size: 0.065, name: Tag128},
    {id: 129, size: 0.065, name: Tag129},
    {id: 130, size: 0.065, name: Tag130},
    {id: 131, size: 0.065, name: Tag131},
    {id: 132, size: 0.065, name: Tag132},
    {id: 133, size: 0.065, name: Tag133},
    {id: 134, size: 0.065, name: Tag134},
    {id: 135, size: 0.065, name: Tag135},
    {id: 136, size: 0.065, name: Tag136},
    {id: 137, size: 0.065, name: Tag137},
    {id: 138, size: 0.065, name: Tag138},
    {id: 139, size: 0.065, name: Tag139},
    {id: 140, size: 0.065, name: Tag140},
    {id: 141, size: 0.065, name: Tag141},
    {id: 142, size: 0.065, name: Tag142},
    {id: 143, size: 0.065, name: Tag143},
    {id: 144, size: 0.065, name: Tag144},
    {id: 145, size: 0.065, name: Tag145},
    {id: 146, size: 0.065, name: Tag146},
    {id: 147, size: 0.065, name: Tag147},
    {id: 148, size: 0.065, name: Tag148},
    {id: 149, size: 0.065, name: Tag149},
    {id: 150, size: 0.065, name: Tag150},
    {id: 151, size: 0.065, name: Tag151},
    {id: 152, size: 0.065, name: Tag152},
    {id: 153, size: 0.065, name: Tag153},
    {id: 154, size: 0.065, name: Tag154},
    {id: 155, size: 0.065, name: Tag155},
    {id: 156, size: 0.065, name: Tag156},
    {id: 157, size: 0.065, name: Tag157},
    {id: 158, size: 0.065, name: Tag158},
    {id: 159, size: 0.065, name: Tag159},
    {id: 160, size: 0.065, name: Tag160},
    {id: 161, size: 0.065, name: Tag161},
    {id: 162, size: 0.065, name: Tag162},
    {id: 163, size: 0.065, name: Tag163},
    {id: 164, size: 0.065, name: Tag164},
    {id: 165, size: 0.065, name: Tag165},
    {id: 166, size: 0.065, name: Tag166},
    {id: 167, size: 0.065, name: Tag167},
    {id: 168, size: 0.065, name: Tag168},
    {id: 169, size: 0.065, name: Tag169},
    {id: 170, size: 0.065, name: Tag170},
    {id: 171, size: 0.065, name: Tag171},
    {id: 172, size: 0.065, name: Tag172},
    {id: 173, size: 0.065, name: Tag173},
    {id: 174, size: 0.065, name: Tag174},
    {id: 175, size: 0.065, name: Tag175},
    {id: 176, size: 0.065, name: Tag176},
    {id: 177, size: 0.065, name: Tag177},
    {id: 178, size: 0.065, name: Tag178},
    {id: 179, size: 0.065, name: Tag179},
    {id: 180, size: 0.065, name: Tag180},
    {id: 181, size: 0.065, name: Tag181},
    {id: 182, size: 0.065, name: Tag182},
    {id: 183, size: 0.065, name: Tag183},
    {id: 184, size: 0.065, name: Tag184},
    {id: 185, size: 0.065, name: Tag185},
    {id: 186, size: 0.065, name: Tag186},
    {id: 187, size: 0.065, name: Tag187},
    {id: 188, size: 0.065, name: Tag188},
    {id: 189, size: 0.065, name: Tag189},
    {id: 190, size: 0.065, name: Tag190},
    {id: 191, size: 0.065, name: Tag191},
    {id: 192, size: 0.065, name: Tag192},
    {id: 193, size: 0.065, name: Tag193},
    {id: 194, size: 0.065, name: Tag194},
    {id: 195, size: 0.065, name: Tag195},
    {id: 196, size: 0.065, name: Tag196},
    {id: 197, size: 0.065, name: Tag197},
    {id: 198, size: 0.065, name: Tag198},
    {id: 199, size: 0.065, name: Tag199},
    {id: 200, size: 0.065, name: Tag200},
    {id: 201, size: 0.065, name: Tag201},
    {id: 202, size: 0.065, name: Tag202},
    {id: 203, size: 0.065, name: Tag203},
    {id: 204, size: 0.065, name: Tag204},
    {id: 205, size: 0.065, name: Tag205},
    {id: 206, size: 0.065, name: Tag206},
    {id: 207, size: 0.065, name: Tag207},
    {id: 208, size: 0.065, name: Tag208},
    {id: 209, size: 0.065, name: Tag209},
    {id: 210, size: 0.065, name: Tag210},
    {id: 211, size: 0.065, name: Tag211},
    {id: 212, size: 0.065, name: Tag212},
    {id: 213, size: 0.065, name: Tag213},
    {id: 214, size: 0.065, name: Tag214},
    {id: 215, size: 0.065, name: Tag215},
    {id: 216, size: 0.065, name: Tag216},
    {id: 217, size: 0.065, name: Tag217},
    {id: 218, size: 0.065, name: Tag218},
    {id: 219, size: 0.065, name: Tag219},
    {id: 220, size: 0.065, name: Tag220},
    {id: 221, size: 0.065, name: Tag221},
    {id: 222, size: 0.065, name: Tag222},
    {id: 223, size: 0.065, name: Tag223},
    {id: 224, size: 0.065, name: Tag224},
    {id: 225, size: 0.065, name: Tag225},
    {id: 226, size: 0.065, name: Tag226},
    {id: 227, size: 0.065, name: Tag227},
    {id: 228, size: 0.065, name: Tag228},
    {id: 229, size: 0.065, name: Tag229},
    {id: 230, size: 0.065, name: Tag230},
    {id: 231, size: 0.065, name: Tag231},
    {id: 232, size: 0.065, name: Tag232},
    {id: 233, size: 0.065, name: Tag233},
    {id: 234, size: 0.065, name: Tag234},
    {id: 235, size: 0.065, name: Tag235},
    {id: 236, size: 0.065, name: Tag236},
    {id: 237, size: 0.065, name: Tag237},
    {id: 238, size: 0.065, name: Tag238},
    {id: 239, size: 0.065, name: Tag239},
    {id: 240, size: 0.065, name: Tag240},
    {id: 241, size: 0.065, name: Tag241},
    {id: 242, size: 0.065, name: Tag242},
    {id: 243, size: 0.065, name: Tag243},
    {id: 244, size: 0.065, name: Tag244},
    {id: 245, size: 0.065, name: Tag245},
    {id: 246, size: 0.065, name: Tag246},
    {id: 247, size: 0.065, name: Tag247},
    {id: 248, size: 0.065, name: Tag248},
    {id: 249, size: 0.065, name: Tag249},
    {id: 250, size: 0.065, name: Tag250},
    {id: 251, size: 0.065, name: Tag251},
    {id: 252, size: 0.065, name: Tag252},
    {id: 253, size: 0.065, name: Tag253},
    {id: 254, size: 0.065, name: Tag254},
    {id: 255, size: 0.065, name: Tag255},
    {id: 256, size: 0.065, name: Tag256},
    {id: 257, size: 0.065, name: Tag257},
    {id: 258, size: 0.065, name: Tag258},
    {id: 259, size: 0.065, name: Tag259},
    {id: 260, size: 0.065, name: Tag260},
    {id: 261, size: 0.065, name: Tag261},
    {id: 262, size: 0.065, name: Tag262},
    {id: 263, size: 0.065, name: Tag263},
    {id: 264, size: 0.065, name: Tag264},
    {id: 265, size: 0.065, name: Tag265},
    {id: 266, size: 0.065, name: Tag266},
    {id: 267, size: 0.065, name: Tag267},
    {id: 268, size: 0.065, name: Tag268},
    {id: 269, size: 0.065, name: Tag269},
    {id: 270, size: 0.065, name: Tag270},
    {id: 271, size: 0.065, name: Tag271},
    {id: 272, size: 0.065, name: Tag272},
    {id: 273, size: 0.065, name: Tag273},
    {id: 274, size: 0.065, name: Tag274},
    {id: 275, size: 0.065, name: Tag275},
    {id: 276, size: 0.065, name: Tag276},
    {id: 277, size: 0.065, name: Tag277},
    {id: 278, size: 0.065, name: Tag278},
    {id: 279, size: 0.065, name: Tag279},
    {id: 280, size: 0.065, name: Tag280},
    {id: 281, size: 0.065, name: Tag281},
    {id: 282, size: 0.065, name: Tag282},
    {id: 283, size: 0.065, name: Tag283},
    {id: 284, size: 0.065, name: Tag284},
    {id: 285, size: 0.065, name: Tag285},
    {id: 286, size: 0.065, name: Tag286},
    {id: 287, size: 0.065, name: Tag287},
    {id: 288, size: 0.065, name: Tag288},
    {id: 289, size: 0.065, name: Tag289},
    {id: 290, size: 0.065, name: Tag290},
    {id: 291, size: 0.065, name: Tag291},
    {id: 292, size: 0.065, name: Tag292},
    {id: 293, size: 0.065, name: Tag293},
    {id: 294, size: 0.065, name: Tag294},
    {id: 295, size: 0.065, name: Tag295},
    {id: 296, size: 0.065, name: Tag296},
    {id: 297, size: 0.065, name: Tag297},
    {id: 298, size: 0.065, name: Tag298},
    {id: 299, size: 0.065, name: Tag299},
    {id: 300, size: 0.065, name: Tag300},
    {id: 301, size: 0.065, name: Tag301},
    {id: 302, size: 0.065, name: Tag302},
    {id: 303, size: 0.065, name: Tag303},
    {id: 304, size: 0.065, name: Tag304},
    {id: 305, size: 0.065, name: Tag305},
    {id: 306, size: 0.065, name: Tag306},
    {id: 307, size: 0.065, name: Tag307},
    {id: 308, size: 0.065, name: Tag308},
    {id: 309, size: 0.065, name: Tag309},
    {id: 310, size: 0.065, name: Tag310},
    {id: 311, size: 0.065, name: Tag311},
    {id: 312, size: 0.065, name: Tag312},
    {id: 313, size: 0.065, name: Tag313},
    {id: 314, size: 0.065, name: Tag314},
    {id: 315, size: 0.065, name: Tag315},
    {id: 316, size: 0.065, name: Tag316},
    {id: 317, size: 0.065, name: Tag317},
    {id: 318, size: 0.065, name: Tag318},
    {id: 319, size: 0.065, name: Tag319},
    {id: 320, size: 0.065, name: Tag320},
    {id: 321, size: 0.065, name: Tag321},
    {id: 322, size: 0.065, name: Tag322},
    {id: 323, size: 0.065, name: Tag323},
    {id: 324, size: 0.065, name: Tag324},
    {id: 325, size: 0.065, name: Tag325},
    {id: 326, size: 0.065, name: Tag326},
    {id: 327, size: 0.065, name: Tag327},
    {id: 328, size: 0.065, name: Tag328},
    {id: 329, size: 0.065, name: Tag329},
    {id: 330, size: 0.065, name: Tag330},
    {id: 331, size: 0.065, name: Tag331},
    {id: 332, size: 0.065, name: Tag332},
    {id: 333, size: 0.065, name: Tag333},
    {id: 334, size: 0.065, name: Tag334},
    {id: 335, size: 0.065, name: Tag335},
    {id: 336, size: 0.065, name: Tag336},
    {id: 337, size: 0.065, name: Tag337},
    {id: 338, size: 0.065, name: Tag338},
    {id: 339, size: 0.065, name: Tag339},
    {id: 340, size: 0.065, name: Tag340},
    {id: 341, size: 0.065, name: Tag341},
    {id: 342, size: 0.065, name: Tag342},
    {id: 343, size: 0.065, name: Tag343},
    {id: 344, size: 0.065, name: Tag344},
    {id: 345, size: 0.065, name: Tag345},
    {id: 346, size: 0.065, name: Tag346},
    {id: 347, size: 0.065, name: Tag347},
    {id: 348, size: 0.065, name: Tag348},
    {id: 349, size: 0.065, name: Tag349},
    {id: 350, size: 0.065, name: Tag350}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
  ]
