origin:
- id: 300
  orientation:
  - 0
  - 0
  - 0
  - 1
  translation:
  - 0
  - 0
  - 0
tiles:
- - curve_left/W
  - straight/W
  - straight/W
  - 3way_left/W
  - straight/W
  - straight/W
  - 3way_left/W
  - straight/W
  - curve_left/N
  - grass
- - straight/S
  - grass
  - grass
  - straight/S
  - grass
  - grass
  - straight/S
  - grass
  - curve_left/S
  - curve_left/N
- - straight/S
  - grass
  - grass
  - straight/S
  - grass
  - grass
  - straight/S
  - grass
  - grass
  - straight/S
- - 3way_left/S
  - straight/W
  - straight/W
  - 4way
  - straight/W
  - straight/W
  - 3way_left/E
  - straight/W
  - straight/W
  - 3way_left/N
- - straight/S
  - grass
  - grass
  - straight/S
  - grass
  - grass
  - grass
  - grass
  - grass
  - straight/S
- - straight/S
  - grass
  - grass
  - curve_left/S
  - straight/W
  - curve_left/N
  - grass
  - grass
  - grass
  - straight/S
- - 3way_left/S
  - straight/W
  - curve_left/N
  - grass
  - grass
  - straight/S
  - grass
  - grass
  - grass
  - straight/S
- - straight/S
  - grass
  - curve_left/S
  - straight/W
  - straight/W
  - 4way
  - straight/W
  - straight/W
  - straight/W
  - 3way_left/N
- - curve_left/S
  - curve_left/N
  - grass
  - grass
  - grass
  - straight/N
  - grass
  - grass
  - grass
  - straight/S
- - grass
  - curve_left/S
  - curve_left/N
  - grass
  - grass
  - curve_left/S
  - straight/W
  - curve_left/N
  - grass
  - straight/S
- - grass
  - grass
  - curve_left/S
  - curve_left/N
  - grass
  - grass
  - grass
  - straight/S
  - grass
  - straight/S
- - grass
  - grass
  - grass
  - straight/S
  - grass
  - curve_left/W
  - straight/W
  - 4way
  - straight/W
  - curve_left/E
- - grass
  - grass
  - grass
  - curve_left/S
  - straight/W
  - curve_left/E
  - grass
  - straight/S
  - grass
  - grass

watchtowers:
- watchtower01
- watchtower02
- watchtower03
- watchtower04
- watchtower05
- watchtower06
- watchtower07
- watchtower08
- watchtower09
- watchtower10
- watchtower11
- watchtower12
- watchtower13
- watchtower14
- watchtower15
- watchtower16
- watchtower17
- watchtower18
- watchtower19
- watchtower20
- watchtower21
- watchtower22
- watchtower23
- watchtower24
- watchtower25
- watchtower26
- watchtower27
- watchtower28
- watchtower29
- watchtower31
- watchtower32
- watchtower33
- watchtower34
- watchtower35
- watchtower36

fixed_tags:
