origin:
- id: 142
  orientation:
  - 0
  - 0
  - 0
  - 1
  translation:
  - 0
  - 0
  - 0
tiles:
- - curve_left/W
  - straight/W
  - straight/W
  - 3way_left/W
  - straight/W
  - straight/W
  - 3way_left/W
  - straight/W
  - curve_left/N
  - grass
- - straight/S
  - grass
  - grass
  - straight/S
  - grass
  - grass
  - straight/S
  - grass
  - curve_left/S
  - curve_left/N
- - straight/S
  - grass
  - grass
  - straight/S
  - grass
  - grass
  - straight/S
  - grass
  - grass
  - straight/S
- - 3way_left/S
  - straight/W
  - straight/W
  - 4way
  - straight/W
  - straight/W
  - 3way_left/E
  - straight/W
  - straight/W
  - 3way_left/N
- - straight/S
  - grass
  - grass
  - straight/S
  - grass
  - grass
  - grass
  - grass
  - grass
  - straight/S
- - straight/S
  - grass
  - grass
  - curve_left/S
  - straight/W
  - curve_left/N
  - grass
  - grass
  - grass
  - straight/S
- - 3way_left/S
  - straight/W
  - curve_left/N
  - grass
  - grass
  - straight/S
  - grass
  - grass
  - grass
  - straight/S
- - straight/S
  - grass
  - curve_left/S
  - straight/W
  - straight/W
  - 4way
  - straight/W
  - straight/W
  - straight/W
  - 3way_left/N
- - curve_left/S
  - curve_left/N
  - grass
  - grass
  - grass
  - straight/N
  - grass
  - grass
  - grass
  - straight/S
- - grass
  - curve_left/S
  - curve_left/N
  - grass
  - grass
  - curve_left/S
  - straight/W
  - curve_left/N
  - grass
  - straight/S
- - grass
  - grass
  - curve_left/S
  - curve_left/N
  - grass
  - grass
  - grass
  - straight/S
  - grass
  - straight/S
- - grass
  - grass
  - grass
  - straight/S
  - grass
  - curve_left/W
  - straight/W
  - 4way
  - straight/W
  - curve_left/E
- - grass
  - grass
  - grass
  - curve_left/S
  - straight/W
  - curve_left/E
  - grass
  - straight/S
  - grass
  - grass

Watchtowers:
- Watchtower01
- Watchtower02
- Watchtower03
- Watchtower04
- Watchtower05
- Watchtower15
fixed_tags:
