origin:
- id: 300
  orientation:
  - 0
  - 0
  - 0
  - 1
  translation:
  - 0
  - 0
  - 0
tiles:
- - 3way_left/S
  - straight/W
  - 3way_left/W
  - straight/W
  - curve_left/N
- - straight/S
  - grass
  - straight/S
  - grass
  - straight/S
- - curve_left/S
  - straight/E
  - 3way_left/E
  - straight/E
  - curve_left/E

watchtowers:
- watchtower12
- watchtower13
- watchtower21
- watchtower25
- watchtower26
- watchtower29
- watchtower32
- watchtower33
- watchtower35
- watchtower36
- watchtower37
- watchtower38
- watchtower40
- watchtower42
- watchtower43
- watchtower47

fixed_tags:
- id: 377
  orientation: 0
  translation: [ 0, 0]
  tile: [6, 8]
- id: 389
  orientation: 0
  translation: [ 24, 0]
  tile: [6, 8]
- id: 383
  orientation: 0
  translation: [ 0, 0]
  tile: [8, 7]
- id: 321
  orientation: 0
  translation: [ 24, 0]
  tile: [8, 7]
- id: 365
  orientation: 0
  translation: [ 0, 0]
  tile: [10, 5]
- id: 371
  orientation: 0
  translation: [ 0, 40]
  tile: [9, 5]
- id: 353
  orientation: 0
  translation: [ 0, 0]
  tile: [5, 6]
- id: 359
  orientation: 0
  translation: [ 0, 0]
  tile: [5, 5]
- id: 313
  orientation: 0
  translation: [ 0, 24]
  tile: [7, 5]
- id: 307
  orientation: 0
  translation: [ 0, 0]
  tile: [6, 5]
- id: 340
  orientation: 0
  translation: [ 25, 0]
  tile: [7, 4]
- id: 345
  orientation: 0
  translation: [ 20, 0]
  tile: [7, 3]
- id: 384
  orientation: 0
  translation: [ 0, 0]
  tile: [7, 2]
- id: 331
  orientation: 0
  translation: [ 0, 40]
  tile: [6, 1]
- id: 328
  orientation: 0
  translation: [ 30, 0]
  tile: [8, 3]
- id: 334
  orientation: 0
  translation: [ 20, 0]
  tile: [8, 4]
- id: 394
  orientation: 0
  translation: [0, 0]
  tile: [9, 0]
- id: 316
  orientation: 0
  translation: [ 32, 0]
  tile: [8, 1]
- id: 337
  orientation: 0
  translation: [ 0, 15]
  tile: [10, 2]
- id: 322
  orientation: 0
  translation: [ 0, 0]
  tile: [9, 2]
- id: 304
  orientation: 0
  translation: [0, 0]
  tile: [0,9]
- id: 339
  orientation: 0
  translation: [ 0, 0]
  tile: [1,9]
- id: 346
  orientation: 0
  translation: [ 0, 0]
  tile: [0, 11]
- id: 352
  orientation: 0
  translation: [ 0, 0]
  tile: [1, 11]
- id: 358
  orientation: 0
  translation: [35,0]
  tile: [1, 11]
- id: 300
  orientation: 0
  translation: [45, 0]
  tile: [1, 12]
- id: 370
  orientation: 0
  translation: [ 15, 0]
  tile: [3, 12]
- id: 364
  orientation: 0
  translation: [ 25, 0]
  tile: [3, 11]
- id: 319
  orientation: 0
  translation: [ 0, 0]
  tile: [3, 9]
- id: 325
  orientation: 0
  translation: [ 20, 17]
  tile: [2, 9]
- id: 351
  orientation: 0
  translation: [ 0, 0]
  tile: [5, 9]
- id: 357
  orientation: 0
  translation: [ 0, 0]
  tile: [4, 9]
- id: 363
  orientation: 0
  translation: [ 0, 0]
  tile: [7,11]
- id: 378
  orientation: 0
  translation: [0,40]
  tile: [7,9]
- id: 376
  orientation: 0
  translation: [ 0, 0]
  tile: [4,12]
- id: 382
  orientation: 0
  translation: [0,34.5]
  tile: [5,11]
- id: 381
  orientation: 0
  translation: [ 0, 0]
  tile: [6,13]
- id: 387
  orientation: 0
  translation: [24,0]
  tile: [6,13]
- id: 375
  orientation: 0
  translation: [ 0,25]
  tile: [6,11]
- id: 308
  orientation: 0
  translation: [25.5, 29]
  tile: [8,8]
- id: 314
  orientation: 0
  translation: [0, 0]
  tile: [9, 9]
- id: 393
  orientation: 0
  translation: [0,0]
  tile: [10,11]
- id: 310
  orientation: 0
  translation: [ 0,15]
  tile: [9, 7]
- id: 369
  orientation: 0
  translation: [0, 15]
  tile: [10, 7]
- id: 327
  orientation: 0
  translation: [ 0, 0]
  tile: [2, 7]
- id: 333
  orientation: 0
  translation: [0, 0]
  tile: [2, 8]
- id: 309
  orientation: 0
  translation: [ 35, 0]
  tile: [3, 7]
- id: 315
  orientation: 0
  translation: [ 40, 0]
  tile: [3, 8]
- id: 302
  orientation: 0
  translation: [0, 25]
  tile: [0,2]
- id: 303
  orientation: 0
  translation: [ 0, 45]
  tile: [1, 6]
- id: 391
  orientation: 0
  translation: [ 0, 62]
  tile: [0, 5]
- id: 347
  orientation: 0
  translation: [ 0, 40]
  tile: [1, 4]
- id: 373
  orientation: 0
  translation: [ 0, 0]
  tile: [2, 4]
- id: 367
  orientation: 0
  translation: [ 0, 30]
  tile: [2, 3]
- id: 355
  orientation: 0
  translation: [ 10, 0]
  tile: [4, 3]
- id: 361
  orientation: 0
  translation: [ 20, 0]
  tile: [4, 4]
- id: 349
  orientation: 0
  translation: [ 0, 0]
  tile: [5, 4]
- id: 343
  orientation: 0
  translation: [ 25, 0]
  tile: [5, 3]
- id: 341
  orientation: 0
  translation: [0, 30]
  tile: [4, 2]
- id: 388
  orientation: 0
  translation: [ 0, 0]
  tile: [3, 2]
- id: 385
  orientation: 0
  translation: [ 0, 0]
  tile: [2, 1]
- id: 395
  orientation: 0
  translation: [ 0, 40]
  tile: [1, 0]
- id: 379
  orientation: 0
  translation: [ 0, 40]
  tile: [1, 2]
- id: 329
  orientation: 0
  translation: [ 0, 0]
  tile: [2, 0]
- id: 335
  orientation: 0
  translation: [40,0]
  tile: [2, 0]
- id: 323
  orientation: 0
  translation: [ 0, 0]
  tile: [5, 1]
- id: 317
  orientation: 0
  translation: [ 10, 0]
  tile: [5, 0]
- id: 305
  orientation: 0
  translation: [ 0, 0]
  tile: [7, 0]
- id: 311
  orientation: 0
  translation: [25, 0]
  tile: [7, 1]
