origin:
- id: 300
  orientation:
  - 0
  - 0
  - 0
  - 1
  translation:
  - 0
  - 0
  - 0
tiles:
- - 3way_left/S
  - straight/W
  - 3way_left/W
  - straight/W
  - curve_left/N
- - straight/S
  - grass
  - straight/S
  - grass
  - straight/S
- - curve_left/S
  - straight/E
  - 3way_left/E
  - straight/E
  - curve_left/E

watchtowers:
- watchtower12
- watchtower13
- watchtower21
- watchtower25
- watchtower26
- watchtower29
- watchtower32
- watchtower33
- watchtower35
- watchtower36
- watchtower37
- watchtower38
- watchtower40
- watchtower42
- watchtower43
- watchtower47

fixed_tags:
- id: 334
  orientation: 0
  translation: [ 30, 38]
  tile: [3, 0]
- id: 340
  orientation: 0
  translation: [ 13.5, 44.7]
  tile: [4, 0]
- id: 337
  orientation: 0
  translation: [ 42.9, 45.3]
  tile: [2, 0]
- id: 328
  orientation: 0
  translation: [ 16.2, 41.7]
  tile: [2, 0]
- id: 382
  orientation: 0
  translation: [ 31.2, 41.3]
  tile: [1, 0]
- id: 381
  orientation: 0
  translation: [ 47.3, 47.3]
  tile: [0, 0]
- id: 307
  orientation: 0
  translation: [ 18.1, 30.7]
  tile: [4, 1]
- id: 313
  orientation: 0
  translation: [ 13.5, 16.1]
  tile: [4, 2]
- id: 383
  orientation: 0
  translation: [ 29.7, 23.8]
  tile: [3, 2]
- id: 321
  orientation: 0
  translation: [ 44.5, 20.2]
  tile: [2, 2]
- id: 371
  orientation: 0
  translation: [ 19.5, 21]
  tile: [2, 2]
- id: 310
  orientation: 0
  translation: [ 41.5, 30.7]
  tile: [2, 1]
- id: 369
  orientation: 0
  translation: [ 19.3, 33.4]
  tile: [2, 1]
- id: 365
  orientation: 0
  translation: [ 30.1, 24.4]
  tile: [1, 2]
- id: 353
  orientation: 0
  translation: [ 40.8, 21.3]
  tile: [0, 2]
- id: 359
  orientation: 0
  translation: [ 38.9, 31.7]
  tile: [0, 1]
