fixed_tags:
- id: 14
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - &id001 !!python/name:numpy.ndarray ''
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - &id002 !!python/object/apply:numpy.dtype
      args:
      - f8
      - 0
      - 1
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - false
    - !!binary |
      O+I+7EwXpT9AwPNqx9fvP7Uufnq5Cbc/6Z6u4U7uAkAxdg3PisLgvxhVLfgmJLk/5rlOXgQU67/s
      C5dCFg4DwDrzS/dhOuu/eMfGo/Mjib/CKwQPns7gPxGkWpA7wOO/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 16
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      sBIf7YDkwb+QxGII81djv9iJfr6Lr++/pqfyS8BnA0DW4iddo6Lvv+gJ5jdRuqy/1EiPZZnhwT/x
      YbswRPXrP5bokW9Tnay/mE1JZRLz7z9eb6YVe5B2PxDzynqrItQ/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 22
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      MvTToNLFlD++E+P6QEzOP/z04Ip3Fe8/8OxFGHUVx7/b0gvv3PPrP3ZOXhh0hN6/Y4N1KWATuT/y
      AP/dewUEwFR2NhaoIN8/FwBPXLcW6z/Q7DwdMrTLvwB3H7d309+/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 324
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      Q7IckqDT77+xB8RpQNG1vzRNGYJGd66/3cTsGsZ6tb9xTgSOcri3P6BNn7hGkO+/HmaM9oBpwb+Z
      R0ltZMD4v+MZr/9bHai/ufHPpAYGwr+AkQ7VMqXvP1nq/tu6n7q/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 29
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      7N8LRyKt77+cv/8stSe+P3oijY55PrQ/JTPJjAsO4j+I1tTjVZWfP5g8poVdYte/oC3BzWjF7T8F
      97mJmNoCwHoLwSrKucE/GBXCqEuM7T/SJtMMSerWP/ZHLxQeluC/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 300
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      AAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 302
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      RXmjT6or7r+mrOoH86fCv/UEmwmALtO/897GGkz46D/wttqcRLDTP/x/ZtaYP+e/7KWDDISp47/F
      QVj8Azv6vzF1chyKaMC/kV5YdBF95b/MnM76p1rnPxYMwWF+t8y/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 303
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      ScbZaeXn7z/kXET+IDiUv8UvH+os9rK/yhQ2SHj78T9Cd+YDDPWfv3YiXdZO5eg/InYlvngU5L/l
      QjNGy7v/v1ddoBeD7LE/OBwmZEgY5D+gE8negc3oP+4Wt756S9u/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 319
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      pwQSprcIsr+DD8qzsuPvP3mvAfzlhaa/qKTSkCnR9D/VkrMhYufvvxJ29wMuX7K/D7VmZu/dnb9P
      ozcGvq7mv5wbW3CMf6C/rlJD2UJnpT9GMozHlPTvPwAFXSraxUE/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 320
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      TxJIfZW4fz+ZbatgZ//vP9rwTqjo8YI/T0BcSgpS6z978wPKKujvvxLqnmA3QIE/jrzJ2NJks7/3
      VqoraTHmv+XYaZ2RabO/LCJv5TOwgb9qoBZqG+jvPyvRSSbSy2O/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 322
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      6HLn/IUyuD9mMwHSE9nvv94Va5hQ7Je/WsMcon3f+D92fUsB1Z/vPxMVqdIRvbg/ijoCWPtKvr9K
      cWvYWlmpvxpNDGUXur4/ZklRgsZgiL91L589McTvPySfmxdxHLY/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 68
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      nhPPEpPgvD+ZTGOFAG/vv6opEAAlJMM/vkts8Qvdq79RFUmas/ztP4ZPI5X/Oqw/PCb6g1UP1r+b
      ow1k8sD7vzx8TQ5JJNU/kIJHffjpxj/VszOGxqftPwhin5+l3Lq/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 327
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      OReC6VL5wT9BPiKxIs7uvzUheF+in82/LwFvQpUO+j+lFxI2ya7vP3vmt2e/k8E/Qg48Ht09nj+m
      L///u8nuP9Bl1q/Zcms/GUDEfVfczb8B7Eg56x3vP29Fh6CcjMY/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 75
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      Ep+Kqkfm7z/u4uev5F+fv0ZX4uXisLI/x50XwRez+j8DHt1X4MKgP3ZlrW93w+W/I+oMWqRv57+X
      +HuoN+b9v3LUZxnZdLI/5hjXqmJw5z+pd3zawanlv6t+HfEtosa/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 332
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      b7KZ8W5Gkb9gvTEitv7vP4J/8Y4Aa3Y/ssbIO/rQ7z9XOgqNOfPvv+BumuG585C/3VP7yA5Mq79h
      XujY4YeIP/W6wSYVP6u/5ArJnywRer9p45flOfTvP0W+fY2kWpI/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 333
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      hqO5Qncoqr/sxAYC/tnvvyr7MJlO37S//NnHWZen9D/AP8soRWbpP3yh/WJ/l4I/TrmDuVl247+N
      0Hrfv5QCwK9EUS9MZeM/AIoe/oyFuL+uy1d7TUTpP/I20HceL+a/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 206
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      ULcq20aQsz8NRnm7oX7Bv+zspKbwmu+/4GAqsfjBAkDzBebZ/g/ovyRcZNKQEeW/7k0T8RfcoD/D
      +TsnoKz9v4Rzbdjl8+S/RD7mbmOv5z9WzlrUbZjDv3S00j9Gi76/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 79
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      8ucl9ZPYr79HxzwHwGa3P8q44ezFze+/4NoDuLsHA0BsE2PhkOzvvxzEQKA//KG/zIOF+e5Prj+6
      bMFq6Gu8v0N25pRXNZ6/ktxf5p/Y7z+ndjV+uue3P/eJ+z6/BcM/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 334
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      JAI0RU905T892DEseLPnP2uYyJRnd6Y/UZFwBuCrsz+MG7+cxZ/nvyJ2Yg2tf+U/JI1r1RXNrr/1
      +uZG88XLv2NbZfUS9LK/UBKEVS5CgD8oSp4fQunvP9OC6MEdyXe/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 215
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      j2i1JFnD7z+71v5YQ5Swv9RnSucmTrq/nOMjXt7r+z/pqWD09VC7v2K/r2XNH6+/V2f9Nf7B779A
      JlzL2a+xvy4JrgqLta0/aGLu2p7f7z8raU0aSTexvyraeu4lCL8/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 360
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      Up+fJCjL77/JUacCHaW8vyBTMQT725K/JoJngvlCBEB4ZpZPCvG8P5Uji2eGru+/8BnEHp9vtb/v
      wyv5lwznP6IQ/temJ4K/HtPWdq3Utb+GndgP1uHvP56icKXmDcU/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 157
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      ZqUaMX/d67/4QS8zzEK9P7mr0+ufmt6/VsTJe3HwwL/J6cTFwWLfv4BJf1dN9MC/cD753lqQ6z9o
      MYIzfuwCwHLHkRHO+qE/4dvmoKaB7z8/LjnAPPDFP28YHiv5b9q/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
origin:
- id: 300
  orientation:
  - 0
  - 0
  - 0
  - 1
  translation:
  - 0
  - 0
  - 0
tiles:
- - curve_left/W
  - straight/W
  - straight/W
  - curve_left/N
  - grass
- - straight/S
  - grass
  - grass
  - straight/N
  - grass
- - straight/S
  - grass
  - grass
  - straight/N
  - grass
- - curve_left/S
  - straight/E
  - straight/E
  - curve_left/E
  - grass
- - grass
  - grass
  - grass
  - grass
  - grass
watchtowers:
- watchtower01
- watchtower02
- watchtower03
- watchtower04
- watchtower05
- watchtower15
