fixed_tags:
- id: 320
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - &id001 !!python/name:numpy.ndarray ''
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - &id002 !!python/object/apply:numpy.dtype
      args:
      - f8
      - 0
      - 1
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - false
    - !!binary |
      aQOFgJxocD9inKNO1P7vP2cRPKdl0ZA/IOU6Tq2U6z+p90mH7/vvv1tOHDcEgHI/2N30q0Prn79l
      u0ttVgrmv329wt6K/Z+/5mNJ3YaukL9TkfDt6frvP9nPTmdEwJA/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 322
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      3cqGFDYHvr/FABXL3c/uP3a+oUwHH8+/E2mGa1BTA0ABnamQepXvvxev+2Ph/7W/inAxMyljwT90
      OHVK0gTnvzTKZVuDIrw/ONrSesVg0D/hChIj4LvuPy16qg2Y8N4/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 68
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      LEEZv/3Ivj+t2bV1hVvvvxULaIA2W8Q/kktzWPeArL8JDSJgW/btP5FWS75uEK4/x1sXjBIo1r+y
      53kN0/76vweyUJswHdU/buX8mY9jyD8PK/WIMpbtP7mDocy+S76/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 342
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      xwwt9JCN1D+oSvdLkU3uP2I32xmkWIY/QpM2EqJm6T8xH+SGty7uv/iYlELniNQ/ZTkGXUENtr9R
      PxZc/Z7zv8W2ZllRx7W/yD+AldHJkT8OuL+1D+HvPxASEdzBy7y/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 327
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      mXABPkeowb9xz8PydK/vP/DVyRvivZe/DFCts8euAkDTLTDml7Hvv/lOpxRxo8G/6Opctm0WgD+/
      gh4vfVv7vwggqDu8xXI/mYKag8afmD98fYCIi/3vP4qSeYn1qeI/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 360
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      12V5M7HW7j8cPaS6q4i/P4fwKwzgUM6/eBX6NS+R9z8W+mcD54S5v7E/TR9Wpu8/yjGomTfZuz8w
      N1af0Nf3v0LH0BQEs88/LKb4GTXLtL8A3Y9W3+TuP1pCSGWLKNQ/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 300
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      AAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 75
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      Dh3gU8Hm7z9uXbJ2bvyzP5yN620QZ3+/5mQ1UX6j+j8SL2+HYQWkPx3g0pSBieK/wrcZZ9AN6r/L
      z9Gm+az8v2fK3hDJaLG/0Zoe38326T9caEAc5JPiv0Td3In5YtO/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 332
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      x9jzag2Ul7/RNB0WfvDvPyzix2DTMq2/BZgPUEm37z+c2GwKefbvv0rjDUBt/pm/xunaKb38pL8v
      S0ExV6R4P1mw915QsKW/udX94muurD9wPgSHxevvP0mcIWFxs6M/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 333
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      YczC/qQCkT+cTr4uXPjvv6rwtmnVZ6Q/WIgKL0XO8z9r/PfJGojrP8aVcqztrXi/qC53uQBP4L/C
      fGWPwXkCwFN1XI0TTeA/Lt8BJg/kpT8SwMMrtoDrP41qBfOyOua/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 334
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      /Ry5KtzW5D/+G62RcDjoP4D7C9IxI6y/+HY2P3Cstz/EEwS7UEfov7PSlrhp1OQ/tAbiT08/mr96
      /l6ryG/MvzhAe+rDw5A/p6zQNQHlrT8fNDKo7PDvPyqI2yI5M5E/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 79
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      BoGb1Im6sD+u17l5MVTWv71X0w6Q6u0/1DnWd4Hj+T8Kt4xGNujvPw+z8YR1fK4/+m6s9IFOqL8z
      /2rIGkblvzrpBFlLBaS/rZiOxLzt7T+gK+D5V4PWP77jfnq/ptQ/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 16
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      idWSa9ILwj8/0o+uaY7Qv1yOQF9nlO4/5CbUExPO+D8jFtLTG6fvP7f4mnllvLM/snruIxMCwL/9
      3QSDcCH6v0124Sa9J6W/yK9Fg+bP7j8E70I4gBLRP6R8plkfud8/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 206
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      ei2TAnGdjj+8/G0kSYKLv7nfyXNY/u+/8HhSLvqnAkAUe46MDI3qvyI41UN13OG/9svwX04ZdL/q
      /Kp2zUj8v7xo7aH+2uG//4Sf9EaM6j+rQTZ21fSTv2bkFuabxdW/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 302
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      ucV+x2q+778dWIW2qyXAv4hi7z/dwHc/VWeUNbVn6D+FZAYBPbawP1D3yRB5puG/CZcPHTec6r8x
      60FER6n5v0Zm1W9+rLs/cWqKyZNi6r+4L7PzwsXhP7NA7OOnjs+/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 22
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      JWF+Y4GVqT8CdYP/eWzQPz1lRi4U4+4/lqLr56Sgyb+a8UNkfcjrP87c8+0QSd+/2hS2X77DtT9C
      qYauuHcDwN7tnsP2l98/FbimFFCu6j9hIJ6IQqXPvxXZUTp+SuC/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 215
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      Kavqc2Ck7j+u/OWA+O3Qv4KNE7uCS72/6Iag12qb+j9vcuj8+wa3vygjneY/Wbo/CIojhRuz779K
      +Pff5Z2Jv25fBOhChtE/HIE98RGv7j8MDBN1piOzP1snICr2184/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 324
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      +KIEsBfL778Phcsgn1S6vyiBYkLiiKi/2Mq+NU/Ys7+twZ0a4t67P372Gmaede+/b2inxxPVwr/n
      vDjbPBv4v2eropdSX6C/SEjI3uNgw7/lz9MOVp3vP3oWS+OHJb2/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 303
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      CzaF5ejr7z8ApJPS2sZjP9TRZ1U+6LG/TAVVeXZ38T8nm6lKVdCnv4VMVElBoeg/fi8qZBNg5L/O
      oTNx1h7/v+x45e9cx6o/Gt1bpu9t5D+oxCYztpLoPxzYVvaJFN2/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 317
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      aMNBDbMPsj9fJV2Z+Bnvv+fB+mPpu8y/ElJn+eEF+T8iRYhEn7bvPybE2hTU3qU/3MJRbhwywD/q
      crhC4j7bv8YnlB70Br2/na/JHoqezb8bp156V+vuPxhJbl3hs8g/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 319
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      hHmvmRB8sr9sjhHudajvP9ohILaQNsC/SlN6f1jN9D+v6Wjfm+rvv/1d5BJ7YbK/4Jvfab/Ufz+R
      bwxM1f3mvyAL7N2jCle/ns21QB0+wD9LFAG0xL3vP9DY4zC2NrI/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
origin:
- id: 300
  orientation:
  - 0
  - 0
  - 0
  - 1
  translation:
  - 0
  - 0
  - 0
tiles:
- - curve_left/W
  - straight/W
  - straight/W
  - curve_left/N
  - grass
- - straight/S
  - grass
  - grass
  - straight/N
  - grass
- - straight/S
  - grass
  - grass
  - straight/N
  - grass
- - curve_left/S
  - straight/E
  - straight/E
  - curve_left/E
  - grass
- - grass
  - grass
  - grass
  - grass
  - grass
watchtowers:
- watchtower01
- watchtower02
- watchtower03
- watchtower04
- watchtower05
- watchtower15
