fixed_tags:
- id: 193
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - &id001 !!python/name:numpy.ndarray ''
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - &id002 !!python/object/apply:numpy.dtype
      args:
      - f8
      - 0
      - 1
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - false
    - !!binary |
      FM54CZiB0T+4a8QZmb/RP3Yfxir5eO0/qJJ4l1iB9z9Z/aSvAnbuP2006RqnZa4/Lv2M4cY807/O
      8INx2ZXxvz4po8k6q8G/MDY5rKav7j9H5r60A7bPv9bNluq4C84/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 194
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      KmgWSQua0L/hWm9RkFPuP2wVQGfpzMc/8ThQmoO19T+6+P7mK5vuv0QVRXSa19G/9zd3tu8qtj+U
      c2e77N76vwNiC9mtI8E/CuDwbnjjw7+556rx0VHvPxLlFi9FAtE/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 195
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      PlTT4phpxT86lYJANYfvvyIuMTrzYKK/za/m264n7T8/iDQwp3XvP6PkcGyg/MQ/rUu/AXbPtD+k
      E6a2Tbn5v0TVvTgy/7K/wo/46+YHqb+ag/NRl9/vPxTehK7deNM/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 132
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      Hmv46POZ7z8G216wXmrDP5gu1LZWbKW/2L2XZzpk4D9rgcZ1qCPCv5c2LkduIu8/ZAWEvMpZxz8g
      Tzld3GQCwFhUo+x3gbE/ng78sgZNxr+wpGRBPG/vP/B/UHOcrtg/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 133
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      Ab20Y8Xpzr/lUuPqOPLuPw+zrYNZkLQ/QnzFIf1c5j8JN18BELvuvwJvZiE6AdC/pPdOIAuVvz9K
      LFc7igb5v4QCeYei18E/QvaUQ9o9qL/EwkGYvqbvP5xjcFyu/NM/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 16
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      ZhrvF8mvpz9J7BOG4dHvv5KwiTV3Z7i/1K5LMK658j8TltsiDOnvPyrA1wuTqaQ/etdSrdIfsD/N
      sMpb0Vflv4k4/oPrGK6/E/DHRe0Uub81vT4gWsrvPw67wUbsd8A/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 168
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      LibRy8Xv5j/FMMP9mirmv8yOimz4fbS/AB2/Le/CAEA5LZJtPFDmPzljJulswuY/LSVQ/gLLtj/A
      IJIn2FSjv6i63dXqbHO/2Ns0mlegvr8b8VWZEsXvPyoSHqXKzbY/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 75
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      PDc/SHpt778OOzDITxnIv6DpOryYb2O/pBh01BpE0b//43XL4RLIP2E3eDi0aO+/+MWKfCjpoT+8
      ajqMYZX3v0Ch4jP2QYK/MrILMqlcoT/d+ZCE9vrvP07wWkocXdU/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 142
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      AAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 143
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      0Rt3cTW/7z+dfhwzk2SXv0W2H8fImL+/f0iFSuqE8z9vzKOOcXWVP6jtQiUT/e8/Cm8oWUr6kL+w
      RB1+oeGrP+2dMd+3rr8/15x6+cVjjD/Qesl5OsDvPxQWT5QPw7c/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 144
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      kNJnxFHH7z+5lpLCuby7PzR8CWmnL6c/3B1jabqR7T+ilcWGSEq9vzi3M3+0WO8/tlXmy7MpxT9W
      KczFPIkCwFgsl3bgFJu/Ve3Pqv+txb+icyxFvIbvP9HpGVrnWdo/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 213
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      Xxvesfh47799QadjhtvAv2SI4OV3t7+///wu93m30T9g8C1YdszCP5rihxjOaO+/txD/6kZbv78l
      p5+4qof0v7v7Er1sALu/1jnXora/wb9XYv7dt4LvP0RxxsStdac/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 57
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      RDj0syvm4z+g2+Cp+ArpP0E6eLoBCZ6/KzfbUp+t0D9IRzJMofTov6PmPLVV6eM/TxTly5lwsT8A
      TNRTG95mv+RH7Z8JUrI/tECPcdT0k79KnXOPb+nvP8BeS1vCEpg/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 153
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      sCuOYcU5hD+AwTDSYvvvv2HFu6S8a6C/1CBLe+8htr+hq1V2LfjvP9SnxEIg/oY/SvvnjE2epb+K
      vule2Irxv2K1OXlhyqU/xHaiKhExoL+jJK7uefTvP8hKcDFfZIM/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 68
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      KS3zDeHJ7r9pqtFCgvjQvzTqeSI6H7A/voEfEOStAUAeuWo10cDQPy6bJEZj1O6/e+aSwrtarb/Y
      V5Z6YoH6v383/oicbLM/4QKjj37No79zqrW8POLvP8kIoY9Yw84/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 219
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      ThaqUUw57z8laawX8PDKPxEKMQlB0K6/woquO7bK1T+UIpjiX5PKvxDBHyDbQu8/Oxed957KqT8P
      fHEY4oPfvwbkIA7qw7E/jqdp+LDEor+SQMNVu+bvP4AoB9pZVqY/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 157
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      AJahk2+kbz/aV8RpL+zJv47H8/kuVu+/PHoddnOu5z//BQfeG/7vv3wFU0LkZJQ/sqJb4++CgL/E
      BIgN9xjxv6otPWevpJU/A6LsL5ZU7z/0McjoIejJv3k4a5v2OLk/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
- id: 215
  transformation: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - b
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 4
      - 4
    - *id002
    - false
    - !!binary |
      aHiE0LVCqb8xcHCQe/Tvv0T3/tBJ2ZM/oSYPhOua/T+tbwye6WHvP5Eh9nSk6qa/xalQ6T1cyD/V
      lsW11bftv7yWQIcLN8i/APyblacUnT9JGhUrtWjvPzEOe5m478M/AAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAA8D8=
origin:
- id: 142
  orientation:
  - 0
  - 0
  - 0
  - 1
  translation:
  - 0
  - 0
  - 0
tiles:
- - curve_left/W
  - straight/W
  - straight/W
  - curve_left/N
- - straight/S
  - grass
  - grass
  - straight/N
- - straight/S
  - grass
  - grass
  - straight/N
- - curve_left/S
  - straight/E
  - straight/E
  - curve_left/E
watchtowers:
- watchtower01
- watchtower02
- watchtower03
- watchtower04
- watchtower05
- watchtower15
