# Parameters for open_loop_intersection_node
# #Turn right through intersection
turn_left: #time, velocity, angular vel
  - [0.8, 0.5, 0]
  - [1.8, 0.5, 3.14]
#  - [0.1, 0.0, 0.0]
  - [0.1, 0.5, 0.0]
turn_right:
  - [0.4, 0.5, 0]
  - [1.25, 0.5, -4.2]
#  - [0.1, 0.0, 0.0]
  - [0.1, 0.35, 0.0]
turn_forward:
  - [2.0, 0.5, 0.0]
  - [0.1, 0.0, 0.0]
  - [0.5, 0.35, 0.0]
# turn_stop:
#   - [0.2, 0.0, 0.0]
