# Parameters for open_loop_intersection_node
# #Turn right through intersection
turn_left: #Time, vel_left, vel_right
  - [1.6, 0.3, 0.4]
  - [0.4, -0.25, 0.25]
  - [1.5, 0.4, 0.4]
turn_right:
  - [1.1, 0.4, 0.4]
  - [0.4, 0.25, -0.25]
  - [0.5, 0.4, 0.4]
turn_forward:
  - [3.0, 0.4, 0.4]
  - [0.0, 0.4, 0.4]
  - [3.0, 0.4, 0.4]
# turn_stop:
#   - [0.2, 0.0, 0.0]
