- name: "dist-est"
  description: "distributed estimation images"
  port: 12345
  pub: "pubtopic"
  sub: "subtopic"
- name: "fleet-plan"
  description: "fleet planning commands"
  port: 23456
  pub: "pubtopic2"
  sub: "subtopic2"
