- name: "fleet-plan-location"
  description: "fleet planning location"
  port: "23333"
  sub: "/taxi/location"
  pub: "dummy1"
- name: "fleet-plan-commands"
  description: "fleet planning commands"
  port: "23334"
  sub: "dummy2"
  pub: "/taxi/commands"
