- name: "fleet-plan-locations"
  description: "fleet planning locations"
  port: "23456"
  sub: "foo"
  pub: "/taxi/location"
- name: "fleet-plan-commands"
  description: "fleet planning commands"
  port: "23457"
  sub: "/taxi/commands"
  pub: "unneeded_dummy"
