- name: "fleet-plan-location"
  description: "fleet planning location"
  port: "23456"
  sub: "/taxi/location"
  pub: "dummy"
- name: "fleet-plan-commands"
  description: "fleet planning commands"
  port: "23457"
  sub: "dummy"
  pub: "/taxi/commands"
