- name: "fleet-plan-locations-1"
  description: "fleet planning locations"
  port: "23000"
  sub: "unneeded_dummy"
  pub: "/taxi/location"
- name: "fleet-plan-commands-1"
  description: "fleet planning commands"
  port: "23001"
  sub: "/taxi/commands"
  pub: "unneeded_dummy"
- name: "fleet-plan-locations-2"
  description: "fleet planning locations"
  port: "23002"
  sub: "unneeded_dummy"
  pub: "/taxi/location"
- name: "fleet-plan-commands-2"
  description: "fleet planning commands"
  port: "23003"
  sub: "/taxi/commands"
  pub: "unneeded_dummy"
- name: "fleet-plan-locations-3"
  description: "fleet planning locations"
  port: "23004"
  sub: "unneeded_dummy"
  pub: "/taxi/location"
- name: "fleet-plan-commands-3"
  description: "fleet planning commands"
  port: "23005"
  sub: "/taxi/commands"
  pub: "unneeded_dummy"
- name: "fleet-plan-locations-4"
  description: "fleet planning locations"
  port: "23006"
  sub: "unneeded_dummy"
  pub: "/taxi/location"
- name: "fleet-plan-commands-4"
  description: "fleet planning commands"
  port: "23007"
  sub: "/taxi/commands"
  pub: "unneeded_dummy"
