version: 2
jobs:
    build:
     docker:
        - image: andreacensi/duckietown-xenial-kinetic:10

     steps:
        - checkout

        - run:
            name: deps
            command: |
                apt install python-frozendict


        - run:
            name: build
            command: |
                # echo PWD = $PWD
                source /opt/ros/kinetic/setup.bash
                make build-catkin-parallel

        - run:
            name: make continuous-integration-tests
            command: |
                source /opt/ros/kinetic/setup.bash
                source $PWD/catkin_ws/devel/setup.bash

                pip install procgraph
                export DUCKIETOWN_ROOT=$PWD
                export HOSTNAME=$HOSTNAME
                make test-circle

        - run:
            name: junit
            command: |
                ./misc/collect-test-artifacts.sh ${CIRCLE_ARTIFACTS} ${CIRCLE_TEST_REPORTS}
        - store_artifacts:
              path: out
              destination: out
