version: 2
jobs:
    build:
     docker:
        - image: andreacensi/duckietown-xenial-kinetic:14
     parallelism: 4
     steps:
        - checkout

        - run:
            name: deps
            command: |
                # apt install -y python-frozendict imagemagick

                # uninstall has the -y
                # pip uninstall -y comptests
                pip install comptests
                ./misc/python_environment.py comptests

                pip install  procgraph

        - run:
            name: build
            command: |
                # echo PWD = $PWD
                source /opt/ros/kinetic/setup.bash
                make build-catkin-parallel

        - run:
            name: make continuous-integration-tests
            command: |
                source /opt/ros/kinetic/setup.bash
                source $PWD/catkin_ws/devel/setup.bash

                export DUCKIETOWN_ROOT=$PWD
                export HOSTNAME=$HOSTNAME
                export DUCKIEFLEET_ROOT=duckiefleet
                export DUCKIETOWN_DATA=duckietown-data
                mkdir -p $DUCKIETOWN_DATA

                git clone git@github.com:duckietown/duckiefleet-fall2017.git $DUCKIEFLEET_ROOT

                make test-download-logs
                make test-circle

        - run:
            name: junit
            when: always
            command: |

                make test-comptests-collect-junit

                # export artifacts=artifacts
                # export reports=reports
                # mkdir -p $artifacts
                # mkdir -p $reports
                # .circleci/collect-test-artifacts.sh $artifacts $reports




        - test-results-store:
                path: out/comptests/junit

        - store_artifacts:
              path: artifacts
              destination: artifacts

        - store_artifacts:
              path: reports
              destination: reports

        - store_artifacts:
              path: out
              destination: out
