version: 2
jobs:
    build:
     docker:
        - image: andreacensi/duckietown-xenial-kinetic:6

     steps:
        - checkout

        - run:
            name: build
            command: |
                # echo PWD = $PWD
                source /opt/ros/kinetic/setup.bash
                make build-parallel

        - run:
            name: run tests
            command: |
                #echo PWD = $PWD
                source /opt/ros/kinetic/setup.bash
                #echo  $PWD/catkin_ws/devel
                #vdir $PWD/catkin_ws/devel
                source $PWD/catkin_ws/devel/setup.bash
                export DUCKIETOWN_ROOT=$PWD
                export HOSTNAME=$HOSTNAME
                make comptests

        - store_artifacts:
              path: out/comptests
              destination: out-comptests
