version: 2
jobs:
    build:
     docker:
        - image: andreacensi/duckietown-xenial-kinetic:10

     steps:
        - checkout

        - run:
            name: build
            command: |
                # echo PWD = $PWD
                source /opt/ros/kinetic/setup.bash
                make build-catkin-parallel

        - run:
            name: make continuous-integration-tests
            command: |
                source /opt/ros/kinetic/setup.bash
                source $PWD/catkin_ws/devel/setup.bash
                export DUCKIETOWN_ROOT=$PWD
                export HOSTNAME=$HOSTNAME
                make test-circle

        - store_artifacts:
              path: out
              destination: out
