version: 2
jobs:
    build:
     docker:
        - image: andreacensi/duckietown-xenial-kinetic:5

     steps:
        - checkout

        - run:
            name: build
            command: |
                source /opt/ros/kinetic/setup.bash
                # apt-get install python-pip
                pip install empy catkin_pkg numpy
                pip install comptests
                make build-parallel

        - run:
            name: run tests
            command: |
                export DUCKIETOWN_ROOT=$PWD
                export HOSTNAME=$HOSTNAME
                source environment.sh
                make comptests

        - store_artifacts:
              path: out/comptests
              destination: out-comptests
