version: 2
jobs:
    build:
     docker:
        - image: andreacensi/duckietown-xenial-kinetic:11

     steps:
        - checkout

        - run:
            name: deps
            command: |
                apt install -y python-frozendict imagemagick


        - run:
            name: build
            command: |
                # echo PWD = $PWD
                source /opt/ros/kinetic/setup.bash
                make build-catkin-parallel

        - run:
            name: make continuous-integration-tests
            command: |
                source /opt/ros/kinetic/setup.bash
                source $PWD/catkin_ws/devel/setup.bash

                pip install procgraph
                export DUCKIETOWN_ROOT=$PWD
                export HOSTNAME=$HOSTNAME
                export DUCKIEFLEET_ROOT=duckiefleet
                export DUCKIETOWN_DATA=duckietown-data
                mkdir -p $DUCKIETOWN_DATA
                git clone git@github.com:duckietown/duckiefleet-fall2017.git $DUCKIEFLEET_ROOT
                make test-circle

        - run:
            name: junit
            command: |
                echo CIRCLE_ARTIFACTS: "$CIRCLE_ARTIFACTS"
                echo CIRCLE_TEST_REPORTS: "$CIRCLE_TEST_REPORTS"
                ./misc/collect-test-artifacts.sh $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
        - store_artifacts:
              path: out
              destination: out
