# Parameters for joy_mapper/joy_mapper
# speed_gain: 0.4293
speed_gain: 0.41
# steer_gain: 8.586
steer_gain: 8.3
bicycle_kinematics: 1.0
steer_angle_gain: 1.04
simulated_vehicle_length: 0.18
vehicule_dynamics: 1.0
mass: 1.0
b: 4.0
I: 0.3
b_ang: 0.1
u_gain: 0.85
t_gain: 1.0
