events:
  at_stop_line:
    topic: "stop_line_filter_node/at_stop_line"
    msg_type: "BoolStamped"
    trigger: True
  velocity_zero: 
    topic: "lane_controller_node/car_cmd"
    msg_type: "Twist2DStamped"
    field: "v"
    trigger: 0.0
  joystick_override_on: 
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: True
  parallel_autonomy_on:
    topic: "joy_mapper_node/parallel_autonomy"
    msg_type: "BoolStamped"
    trigger: True
  parallel_autonomy_off:
    topic: "joy_mapper_node/parallel_autonomy"
    msg_type: "BoolStamped"
    trigger: False
  # apriltag_sign_type:
  #   topic: "apriltag_node/apriltags_out"
  #   msg_type: "AprilTagsWithInfos"
  #   field: infos.tag_type
  #   trigger: 1
  # apriltag_parking:
  #   topic: "apriltag_node/apriltags_out"
  #   msg_type: "AprilTagsWithInfos"
  #   field: infos.traffic_sign_type
  #   trigger: 19
  # apriltag_fourway:
  #   topic: "apriltag_node/apriltags_out"
  #   msg_type: "AprilTagsWithInfos"
  #   trigger: 11
  # apriltag_right_t:
  #   topic: "apriltag_node/apriltags_out"
  #   msg_type: "AprilTagsWithInfos"
  #   trigger: 12
  # apriltag_left_t:
  #   topic: "apriltag_node/apriltags_out"
  #   msg_type: "AprilTagsWithInfos"
  #   trigger: 13
  # apriltag_t:
  #   topic: "apriltag_node/apriltags_out"
  #   msg_type: "AprilTagsWithInfos"
  #   trigger: 14

# TODO: 
# - check whether non-Bool values can be given. 
# - check correct topic of velocity

gates:
  at_stop_line_and_velocity_zero:
    gate_type: "AND"
    inputs:
      - at_stop_line
      - velocity_zero
    output_topic: "~at_stop_line_and_velocity_zero"
  apriltag_parking_and_parking_active:
    gate_type: AND
    inputs:
      - apriltag_parking
      - apriltag_sign_type
      - parking_active
    output_topic: "~apriltag_parking_and_parking_active"
  apriltag_intersection:
    gate_type: OR
    inputs:
      - apriltag_fourway
      - apriltag_right_t
      - apriltag_left_t
      - apriltag_t
    output_topic: "~apriltag_intersection"
  joystick_override_on_and_parallel_autonomy_off:
    gate_type: AND
    inputs:
      - joystick_override_on
      - parallel_autonomy_off
    output_topic: "~joystick_override_on_and_parallel_autonomy_off"
  joystick_override_on_and_parallel_autonomy_on:
    gate_type: AND
    inputs:
      - joystick_override_on
      - parallel_autonomy_off
    output_topic: "~joystick_override_on_and_parallel_autonomy_on"
