events:
  at_stop_line:
    topic: "stop_line_filter_node/at_stop_line"
    trigger: True
  velocity_zero: 
    topic: "car_cmd/V"
    trigger: 0
# TODO: 
# - check whether non-Bool values can be given. 
# - check correct topic of velocity

gates:
  at_stop_line_and_velocity_zero:
    gate_type: "AND"
    inputs:
      - at_stop_line
      - velocity_zero
      output_topic: "~at_stop_line_and_velocity_zero"