time_left_turn: 3.5
time_straight_turn: 2
time_right_turn: 2

ff_left: 0.1
ff_straight: 0
ff_right: -1.8

LFparams_left: {phi_max: -0.5, phi_min: -2, range_est: 0.6, red_to_white: true, use_yellow: false}
LFparams_straight: {"red_to_white": True}
LFparams_right: {"red_to_white": False}

omega_min_left: -1.5
omega_max_left: 0.8
omega_min_straight: -1
omega_max_straight: 1
omega_min_right: -1
omega_max_right: 1

debug_dir: -1
