# default parameters for lane_filter/lane_filter_node

# change to your robot name below
filter:
  - dt_filtering_duckduckgo.LaneFilterPF
  - configuration:
      example1: 0.2
      mean_d_0: 0
      mean_phi_0: 0
      sigma_d_0: 0
      sigma_phi_0: 0
      delta_d: 0.02
      delta_phi: 0
      d_max: 0.5
      d_min: -0.7
      phi_min: -1.5707
      phi_max: +1.5707
      cov_v: 0.5
      cov_omega: 0.01
      linewidth_white: 0.04
      linewidth_yellow: 0.02
      lanewidth: 0.4
      n_particles: 1000
