# default parameters for lane_filter/lane_filter_node

# change to your robot name below
object_detector:
  inference_graph_path: models/mobilenets_ssd.pb
  score_threshold: 0.2
  denormalize_boundingbox: True


