drive_time: 12000
charge_time: 12000
charger: 3
v_charger_entrance: 0.1
v_charger_inside: 0.4
charger_k_Id: 0.1

charging_stations:
  station1:
    path_in:
      - - 231
        - 2
    path_out:
      - - 240
        - 1
      - - 237
        - 1
      - - 233
        - 1
  station2:
    path_in:
      - - 231
        - 1
      - - 235
        - 2
    path_out:
      - - 239
        - 0
      - - 237
        - 1
      - - 233
        - 1
  station3:
    path_in:
      - - 231
        - 1
      - - 235
        - 1
      - - 238
        - 2
    path_out:
      - - 236
        - 0
      - - 233
        - 1
  station4:
    path_in:
      - - 231
        - 1
      - - 235
        - 1
      - - 238
        - 1
    path_out:
      - - 232
        - 0


maintenance_entrance:
  - - 14400
    - 2
  - - 13500
    - 1

maintenance_exit:
  - - 6400
    - 1
  - - 6400
    - 0

charger_FIL_tags:
  - 244
  - 245
  - 246
  - 247
  - 199
