tags:
  tag300:
    #position:
    - 0   #x
    - 2   #y
    - 4   #z
    #orientation:
    - 0   #roll
    - 0   #pitch
    - 3.14159  #yaw
  tag301:
    - 12
    - 14
    - 16

    - 0
    - 0
    - 22
  tag302:
    - 12
    - 14
    - 16

    - 0
    - 0
    - 22

  tag303:
    - 12
    - 14
    - 16

    - 0
    - 0
    - 22
